# docker run -d --name mi-mysql -v mi-mysql-vol:/var/lib/mysql --net mi-mysql-red --ip 172.25.0.2 -e MYSQL_ROOT_PASSWORD=2daw mongo
services:
  mi-mysql:
    image: mysql
    container_name: mi-mysql 
    stdin_open: true 
    tty: true 
    networks:
      mi-mysql-red: 
        ipv4_address: 172.25.0.2 
    volumes:
      - mi-mysql-vol:/var/lib/mysql 
    environment:
      - MYSQL_ROOT_PASSWORD=2daw 
# docker run --name mi-dashboard --net mi-mysql-red -d -p 8080:80 -e PMA_HOST=172.25.0.2 -e PMA_PORT=3306 -e PMA_USER=root -e PMA_PASSWORD=2daw phpmyadmin/phpmyadmin
  mi-dashboard:
    image: phpmyadmin/phpmyadmin
    container_name: mi-dashboard 
    stdin_open: true 
    tty: true 
    networks:
      mi-mysql-red:
    ports:
      - "8080:80" 
    environment:
      - PMA_HOST=172.25.0.2 
      - PMA_PORT=3306
      - PMA_USER=root 
      - PMA_PASSWORD=2daw 
    
networks:
  mi-mysql-red:
    ipam:
      driver: default 
      config:
        - subnet: 172.25.0.0/16 
      
volumes:
  mi-mysql-vol: